name: Tests

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Run tests with no-std
        run: cargo test -p latches --no-default-features --features task --features futex --features sync
      - name: Runn tests with std
        run: cargo test -p no-std-tests -p latches --all-features
